### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by billhsia** [jeetp465/Aspect-Based-Sentiment-Analysis#1]
hello ,nice to meet u !!  I'm a student from Taiwan , i have some questions about this experiment
Whats your idea about the cnn model , the part of output layer?
It looks like classify the terms of each sentence to 69 classes , not a binary classification for each term .
Can u share your ideas about it? thanks a lot

**Comment by jeetp465** [comment]
It does not classify each term to 69 classes. We have appended padding terms to each sentence to make the length of each sentence equal to the sentence having max length (in this case it is 69) and since the input to the network is this sentence, the probability distribution is drawn over all 69 terms indicating how likely it is for each term to be an aspect. This was the general idea. Please correct me if you find any flaw in this since I was also learning during that phase.
