### ISSUE TITLE
regarding results

### ISSUE THREAD

**Issue by nkooli** [jeetp465/Aspect-Based-Sentiment-Analysis#2]
Hello,

Thank you for sharing this code.
I am interesseted on the problem of aspect term extraction on SemEval dataset. I tested the a CNN model and do not achieve results reported in the paper "Aspect extraction for opinion mining with a deep convolutional neural network"

Have you reworked this code and enhanced the obtained results ?
Thank you

**Comment by jeetp465** [comment]
Hi,

Even I was not able to replicate the results mentioned in the paper. On
discussion with the author, he suggested not to use a vanilla CNN, rather
use CNN for text classification. For my project that time, I didn't require
to go that deep. Try using his suggestion, maybe you'll be able to achieve
better results than what I have obtained.

Regards,
Jeet Patel

On Jan 4, 2018 9:08 PM, "nkooli" <notifications@github.com> wrote:

Hello,

Thank you for sharing this code.
I am interesseted on the problem of aspect term extraction on SemEval
dataset. I tested the a CNN model and do not achieve results reported in
the paper "Aspect extraction for opinion mining with a deep convolutional
neural network"

Have you reworked this code and enhanced the obtained results ?
Thank you

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jeetp465/Aspect-Based-Sentiment-Analysis/issues/2>, or mute
the thread

**Comment by nkooli** [comment]
Can you explain more what is the difference between vanilla CNN and CNN ?
Thank you

**Comment by tusharaherkar** [comment]
Hello can I get any contact details of you. Actually I have doubt regarding this project!

**Comment by jeetp465** [comment]
Hi,

You can reach me on 8400394962 (WhatsApp)

Regards,
Jeet
